use crate::core::crypto::jwt;
use crate::core::errors::app_error::AppError;
use crate::core::security::hash_password::{hash_password, verify_password};
use crate::modules::auth::application::token_service::generate_token_pair;
use crate::modules::auth::domain::auth_result::{LoginResult, RegisterResult};
use crate::modules::auth::domain::session::new_session::NewSession;
use crate::modules::auth::infrastructure::repositories::session_repository::insert_session;
use crate::modules::auth::infrastructure::repositories::user_repository::UserRepository;
use crate::modules::mfa::infrastructure::repositories::mfa_repository;
use jsonwebtoken::EncodingKey;
use uuid::Uuid;

// IMPORTANT:
// Replace this with a real Argon2id hash generated by your own hash_password("dummy-password").
// This must be valid, otherwise timing protection is useless.
const DUMMY_PASSWORD_HASH: &str = "$argon2id$v=19$m=19456,t=2,p=1$c29tZXNhbHQxMjM0NTY3OA$L8F7r3vV5pQ0xGgB6XhH6YxBt0KxXrN5Gz9N9mX3s7A";

// ---------------------------------------------------------------------------
// REGISTER
// ---------------------------------------------------------------------------

pub async fn register_user(
    pool: &sqlx::PgPool,
    email: String,
    password: String,
) -> Result<RegisterResult, AppError> {
    let email = normalize_email(email);

    if email.is_empty() || password.trim().is_empty() {
        return Ok(RegisterResult::InvalidCredentials);
    }

    if password.len() < 12 {
        return Ok(RegisterResult::WeakPassword);
    }

    if email.len() > 254 || password.len() > 1024 {
        return Ok(RegisterResult::InvalidCredentials);
    }

    let hashed = hash_password(&password)?;

    match UserRepository::create_user(pool, &email, &hashed).await {
        Ok(_) => Ok(RegisterResult::Success),

        Err(sqlx::Error::Database(db_err)) if db_err.code().as_deref() == Some("23505") => {
            Ok(RegisterResult::EmailAlreadyExists)
        }

        Err(_) => Err(AppError::DatabaseError),
    }
}

// ---------------------------------------------------------------------------
// LOGIN
// ---------------------------------------------------------------------------

pub async fn login_user(
    pool: &sqlx::PgPool,
    encoding_key: &EncodingKey,
    refresh_secret: &str,
    email: String,
    password: String,
    user_agent: String,
    ip_address: std::net::IpAddr,
) -> Result<LoginResult, AppError> {
    let email = normalize_email(email);

    if email.is_empty() || password.trim().is_empty() {
        return Ok(LoginResult::InvalidCredentials);
    }

    if email.len() > 254 || password.len() > 1024 {
        return Ok(LoginResult::InvalidCredentials);
    }

    let user = match UserRepository::find_by_email(pool, &email).await? {
        Some(user) => user,
        None => {
            let _ = verify_password(&password, DUMMY_PASSWORD_HASH);
            return Ok(LoginResult::InvalidCredentials);
        }
    };

    if !verify_password(&password, &user.password)? {
        return Ok(LoginResult::InvalidCredentials);
    }

    // If MFA is enabled, do NOT issue access/refresh tokens yet.
    // Issue only a short-lived MFA challenge token.
    if let Some(mfa) = mfa_repository::find_by_user_id(pool, user.id).await? {
        if mfa.enabled {
            let mfa_token = jwt::generate_mfa_token(encoding_key, user.id)?;
            return Ok(LoginResult::MfaRequired { user_id: user.id, mfa_token });
        }
    }

    issue_full_login_tokens(
        pool,
        encoding_key,
        refresh_secret,
        &user,
        user_agent,
        ip_address,
    )
    .await
}

// ---------------------------------------------------------------------------
// FULL TOKEN ISSUANCE
// ---------------------------------------------------------------------------

pub async fn issue_full_login_tokens(
    pool: &sqlx::PgPool,
    encoding_key: &EncodingKey,
    refresh_secret: &str,
    user: &crate::modules::auth::models::user_model::User,
    user_agent: String,
    ip_address: std::net::IpAddr,
) -> Result<LoginResult, AppError> {
    let family_id = Uuid::new_v4();
    let rotated_from = None;

    let tokens = generate_token_pair(user, encoding_key, refresh_secret)?;

    let device_name = extract_device_name(&user_agent);

    insert_session(
        pool,
        NewSession {
            user_id: user.id,
            refresh_token_hash: tokens.refresh_token_hash,
            device_name,
            ip_address,
            user_agent,
            jti: tokens.jti,
            family_id,
            rotated_from,
        },
    )
    .await?;

    Ok(LoginResult::Success {
        user_id: user.id,
        access_token: tokens.access_token,
        refresh_token: tokens.refresh_token,
        jti: tokens.jti,
    })
}

// ---------------------------------------------------------------------------
// LOGOUT
// ---------------------------------------------------------------------------

pub async fn logout(pool: &sqlx::PgPool, jti: Uuid) -> Result<(), AppError> {
    crate::modules::auth::infrastructure::repositories::session_repository::revoke_session(
        pool, jti,
    )
    .await
    .map_err(|_| AppError::DatabaseError)?;

    Ok(())
}

pub async fn logout_all(pool: &sqlx::PgPool, user_id: i64) -> Result<(), AppError> {
    crate::modules::auth::infrastructure::repositories::session_repository::revoke_all_user_sessions(
        pool,
        user_id,
    )
    .await
    .map_err(|_| AppError::DatabaseError)?;

    Ok(())
}

// ---------------------------------------------------------------------------
// HELPERS
// ---------------------------------------------------------------------------

fn normalize_email(email: String) -> String {
    email.trim().to_lowercase()
}

fn extract_device_name(user_agent: &str) -> String {
    user_agent
        .split_whitespace()
        .next()
        .unwrap_or("unknown-device")
        .chars()
        .take(64)
        .collect()
}
